### ISSUE TITLE
So I tried to create some indipendet branches with different pull requests but I failed with creating a clean git history

### ISSUE THREAD

**Issue by mogoh** [valknight/TwitchTTS#6]
I have create several branches with different features. You can check them out here:

https://github.com/mogoh/TwitchTTS/branches

If you wish to have a clean history, then I can rebase them.
This is, of course, only if you wish to have them merged in the first place.

**Comment by mogoh** [comment]
Is this abandoned?
Because if so, I will rename my fork and stop doing pull requests.

**Comment by valknight** [comment]
I'm so sorry! Github didn't send me the notif for this - let me check them out now!

**Comment by mogoh** [comment]
Ah great. I will send some more pull requests. most of it is refactoring. I will create some more to better discuss them.
